remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
title: Permutation Limited
description: Software Solutions, Limited Possibilities
logo: /assets/PermutationLimited.png

# Disable "View on Github"
github:
  is_project_page: false